{% set name = "bawk" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source: 
  path: ../src

requirements:
  host:
    - perl
  run:
    - perl


about:
  home: https://github.com/bidauxpoto/bawk
  summary: A wrapper on gawk that implement the ability to name the columns of the input file according to the header